### ISSUE TITLE
The game does not end when you have 21.

### ISSUE THREAD

**Issue by shashvathsrivatsa** [alanfortlink/blackjack.nvim#10]

**Comment by alanfortlink** [comment]
Hey, thanks for bringing this up. This game can still end in a draw, right? Or am I missing something?

**Comment by shashvathsrivatsa** [comment]
Yeah I think it can still end in a draw, but I'm saying that if the user hits 21, the game should automatically end and call it a win for the user. However, if the user has 21, the game keeps going on.

**Comment by alanfortlink** [comment]
I see... I wasn't aware of that rule. I actually like the draw with 21... If you would like to propose the changes in a PR, I'd be happy to review it and merge, otherwise I'll probably leave it as it is.
