### ISSUE TITLE
add randomseed

### ISSUE THREAD

**Issue by max397574** [alanfortlink/blackjack.nvim#2]
if you don't use a different randomseed every time you generate random numbers they won't actually be random
you should add a `math.randomseed(os.clock())` here https://github.com/alanfortlink/blackjack.nvim/blob/0968a1998d0bb1793561fe491d20eaa73e63812a/lua/blackjack/match.lua#L96

you can test this out by doing a few `:lua =math.random(52)` and then restarting neovim and doing it again
the numbers will be the same

**Comment by alanfortlink** [comment]
That should address the issue. I'm setting the seed for every new card deck. Thanks for the tip!
