### ISSUE TITLE
Can't interact with shortcuts

### ISSUE THREAD

**Issue by ned-si** [alanfortlink/blackjack.nvim#5]
Hey there,

When I open `:BlackJackNewGame`, I find myself in normal mode inside the window and <kbd>j</kbd> and <kbd>k</kbd> just move the cursor. I can enter insert mode and change the buffer also, which is not that great. The only way for me to actually play is then to use `:BlackJackOption1` or `[...]2`. 

Do you know what's wrong and how I could fix it?

Thanks in advance!

**Comment by alanfortlink** [comment]
Where are you playing it? Windows/Mac/Linux? What terminal? Can you give me more information?

**Comment by ned-si** [comment]
Sure, sorry, thought about editing my post to add actual information... and then forgot. -.-

- Linux (Arch)
- Kitty
- Tmux
- Zsh
- NVIM v0.9.0-dev-769+g0f52e2c849

And [here](https://github.com/ned-si/dotfiles/tree/master/nvim) are my nvim dotfiles.

**Comment by alanfortlink** [comment]
Hey, thanks for the info. I won't be able to go through your dotfiles and check but I skimmed through and saw that you have some remappings of `j` and `k`. Maybe that has something to do with it?

I tried `kitty` -> `tmux` -> `zsh` -> `nvim` and it worked fine (I don't use arch, btw :P).

Let me know if I can help with anything!

**Comment by ned-si** [comment]
Hey! 

Thanks for checking. I already had similar issues with other buffers and thought that the problem might be related to some settings, but thanks to you I checked all the remaps, and it turns out it's because of [this one](https://github.com/ned-si/dotfiles/blob/master/nvim/lua/nedsi/remap.lua#L19):

```
vim.keymap.set({'n', 'v'}, ':', ";")
```

I absolutely have no idea how come it can be the issue. Are remaps interacting in any way with a new buffer?!

**Comment by alanfortlink** [comment]
I'm not sure myself :/. I map `j` and `k` inside of the buffer to control the game but if it's been set before it could potentially cause the issue? Anyway, from what I understood it's working now, right? If so I'll close the issue :)

**Comment by ned-si** [comment]
So, I tried to remove the remaps for <kbd>j</kbd> and <kbd>k</kbd> but it didn't change anything, I still had the issue. It's really the line I said that was the only problem for some reason. 

Sure, all good now, thanks again for the plugin!
