### ISSUE TITLE
Can go into insert/replace mode

### ISSUE THREAD

**Issue by juiceDeLemon** [alanfortlink/blackjack.nvim#7]
title, causes inconvenience

**Comment by juiceDeLemon** [comment]
thank you for this, you fed my blackjack addiction

**Comment by alanfortlink** [comment]
Hey, how do you think it should work? Do you mean just disabling that ability?
I tried to be careful to not overstep my grounds in the way you use neovim but I can put something as an option if I have the time.

**Comment by juiceDeLemon** [comment]
like in an `:LspInfo` popup (and many others), it will show this message and remain in normal mode upon pressing `i`: `E21: Cannot make changes, 'modifiable' is off`. 

> I tried to be careful to not overstep my grounds in the way you use neovim but I can put something as an option if I have the time.

i don't think it will overstep the way user use neovim since it only affects the game window, and you already have `q` to exit. and i don't think anyone will write anything in the blackjack game window. thanks again

edit: if you don't have the time, it's alright. it's not a big deal. i might find how to do it after i finish my school test

**Comment by alanfortlink** [comment]
Hey, I pushed some changes today to make it `nomodifiable`. Let me know if that's what you were looking for. @juiceDeLemon

**Comment by juiceDeLemon** [comment]
yes that's what i wanted. thanks!
